### PR TITLE
Added few more test sets

### PR DESCRIPTION
**Pull request by Abdullahjavednesar**

### CODE REVIEW

**Comment by arihantparsoya** [comment]
There are 250+ commits in this PR.

**Comment by arihantparsoya** [comment]
I think you should fork my repo first. then send a PR.

**Comment by arihantparsoya** [comment]
send pr to `rubi4`  branch. You are sending PR to my master branch

**Comment by Abdullahjavednesar** [comment]
How should I send it to your rubi4 branch

**Comment by Abdullahjavednesar** [comment]
Okay wait

**Pull request closed without merging**
